sources = ['abc-news','al-jazeera-english','ars-technica','associated-press','axios',
    'bleacher-report','bloomberg','breitbart-news','business-insider','buzzfeed',
    'cbs-news','cnbc','cnn','crypto-coins-news',
    'engadget','entertainment-weekly','espn','espn-cric-info',
    'fortune','fox-news','fox-sports',
    'google-news',
    'hacker-news',
    'ign',
    'mashable','medical-news-today','msnbc','mtv-news',
    'national-geographic','national-review','nbc-news','new-scientist','newsweek','new-york-magazine','next-big-future','nfl-news','nhl-news',
    'politico','polygon',
    'recode','reddit-r-all','reuters',
    'techcrunch','techradar','the-american-conservative','the-hill','the-huffington-post','the-new-york-times','the-next-web','the-verge','the-wall-street-journal','the-washington-post','the-washington-times','time',
    'usa-today',
    'vice-news',
    'wired']