version: 0.0
os: linux
files:
  - source: /
    destination: /srv/comps
hooks:
  BeforeInstall:
    - location: ./beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./install.sh
      timeout: 300
      runas: ubuntu
